### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by JuhQ** [pzanni/sport-matchmaker#9]
Huomioita

Sivuston käytettävyys
  - design selkeä mutta ihan heti konsepti ei aukea
    - konsepti aukeaa kun lukee readmen, mutta pekka peruskäyttäjä ei readmeta nää :(
  - rekisteröinti ei taida antaa virhetilanteista viestiä?
    - laitoin salasanan tarkoituksella väärin ja nappi pysyy disabloituna mutta muuta indikaatiota ei ole
      - ok, tämä olikin näemmä vaan ainoa keissi jossa virheilmoa ei tule
  - rekisteröitymisen jälkeen omaa nimeä ei näy käyttäjälistassa?
    - reloadin jälkeen näytti toimivan
  - hyvä että kirjautuu automaattisesti sisään rekisteröitymisen jälkeen
  - `Show` palkin inputtien labelit olisi kiva olla klikattavia
  - idea alareunan `Made by Anton & Anni` tekstiin: nimet voisi olla klikattavia ja viedä tekijöiden profiiliin?
  - oma profiilisivu ei näytä olevan responsiivinen

Backend
  - ensimmäinen firebase appi joka kurssilla tullut vastaan, tosi jees!

Frontend
  - kurssin opit selkeästi opittu!
  - Niin monta testiä! Todella hyvä
    - muutama testeistä oli jäänyt tyhjiksi/varustettu todo kommenteilla
  - yhdessä testissä oli rivi `expect(header).toEqual('Sign in')`
    - mielestäni tässä `header` muuttujalle parempi nimi olisi `headerText`, jotta käy jo muuttujasta ilmi että kyseessä on otsikkoteksti eikä esimerkiksi otsikon dom-elementti
  - es6:n toiminnallisuutta hyödynnetty hienosti
  - reducers/users.js tiedostossa on funktio `fetchAndSetFirebaseUsers` jossa on tehty arrayhin pushaaminen foreachin kanssa. Tämä olisi hyvä muuttaa muodosta
    ```
    const userArray = []
    snapshot.forEach((childSnapshot) => {
      userArray.push({
        id: childSnapshot.key,
        ...childSnapshot.val()
      })
    })
    ```
    muotoon

    ```
    const userArray = snapshot.map((childSnapshot) => ({
      id: childSnapshot.key,
      ...childSnapshot.val()
    })
    ```
    - Kuten huomaat, koodi yksinkertaistuu ja samalla saadaan sivueffekti pois foreachin sisällä. Foreachia olisi hyvä käyttää esimerkiksi asioiden printtaamiseen tai vaikka logittamiseen, tällaisessa tapauksessa kannattaa suosia mappausta
  - reduxia on käytetty hyvin
  - firebase/firebase.js tiedostossa näyttäisi olevan jotain (tuotanto??) avaimia
  - hui, components/Message.js:n styles objekti on melko pitkä! Tämän voisi rivittää :)
  - components/App.js:ssä tehdään funktiomääritys render metodin sisällä, tämä ei ole välttämättä performanssin kannalta järkevintä
  - välillä stringipropseja passataan tuplahipsuilla ja välillä yksittäisillä hipsuilla, eli `"` tai `'`
    - react komponentteihin kannattaa nuo stringit passata tuplahipsuilla, tai päättää käyttää vain yhtä näistä tavoista eikä sotkea samaan codebaseen kahta eri tapaa sekaisin
  - kun koodissa pitää propsien takia rivittää komponentteja, olisi hyvä että aloitus ja lopetustagit on samalla sisennyksellä jotta on helpompi nähdä mistä kutsu alkaa ja minne se loppuu. Eli
    ```
    <ChallengeVisibilityFilter
      filter={filter}
      dispatchableFunction={dispatchableFunction}
      firstOption={firstOption}
      secondOption={secondOption}
      thirdOption={thirdOption} />
    ```
    muotoon
    ```
    <ChallengeVisibilityFilter
      filter={filter}
      dispatchableFunction={dispatchableFunction}
      firstOption={firstOption}
      secondOption={secondOption}
      thirdOption={thirdOption}
    />
    ```
  - tämmöisissä tilanteissa voisi myös käyttää mappia hyödyksi
    ```
    for (let i = 0; i < 2; i++) {
      for (let j = 0; j < setAmount; j++) {
        const inputField = <input key={j} size={1} maxLength={1} onChange={(event) => changeScoreBoard(i, j, event)} defaultValue={0} onFocus={handleFocus} />
        board[i].push(inputField)
      }
    }
    ```

Suosittelen eslintin käyttöönottoa airbnb konffin kanssa ja ottamaan eslint-disable-line kommentit pois ja korjaamaan nuo ongelmat.
Kannattaa myös asentaa editoriin eslint plugin jolloin näät virheet devatessa.

**Comment by AventusM** [comment]
Kiitoksia kommenteista!!
